apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: ai-gitops

spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc

  project: default

  source:
    repoURL: https://github.com/YOUR_USERNAME/ai-gitops-platform
    targetRevision: HEAD
    path: k8s

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
